import { test, expect } from '@playwright/test';
import { createTestTournament, signInAsTestTournament } from './helpers/testTournament';

test.describe('public spectator brackets', () => {
  test('a bracket generated by the organizer is visible read-only to an anonymous spectator via ?live=true', async ({ page, request, browser }) => {
    const tournament = await createTestTournament(request);
    await signInAsTestTournament(page, tournament);
    await page.goto('/');

    // Add two athletes into the same (default) Rooster weight category.
    const addAthlete = async (name: string, weight: string) => {
      await page.getByTitle(/Athletes|Атлеты/i).click();
      await page.getByRole('button', { name: /Add Athlete|Добавить атлета/i }).click();
      await page.locator('input[placeholder="Иван Иванов"]').fill(name);
      await page.locator('input[placeholder="88.3"]').fill(weight);
      await page.getByRole('button', { name: /^Register$|^Зарегистрировать$/i }).click();
    };
    await addAthlete('Spectator Visible Athlete A', '50');
    await addAthlete('Spectator Visible Athlete B', '55');

    // Generate a bracket for that category.
    await page.getByTitle(/Brackets|Сетки/i).click();
    const categorySelect = page.locator('select').filter({ has: page.getByRole('option', { name: /All Divisions|Все категории/i }) });
    let roosterOption: string | undefined;
    await expect.poll(async () => {
      const options = await categorySelect.locator('option').allTextContents();
      roosterOption = options.find(o => /Rooster/.test(o) && /\(\d+\/2\)/.test(o));
      return roosterOption;
    }, { timeout: 8000 }).toBeTruthy();
    await categorySelect.selectOption({ label: roosterOption! });
    await page.getByRole('button', { name: /Build Bracket|Создать сетку/i }).click();
    await expect(page.locator('text=Spectator Visible Athlete A')).toBeVisible({ timeout: 8000 });

    // Anonymous spectator, no tokens at all, separate browser context.
    const spectatorContext = await browser.newContext();
    const spectatorPage = await spectatorContext.newPage();
    await spectatorPage.goto(`/?live=true&t=${tournament.slug}`);

    // The category dropdown is local UI state per page load — the spectator
    // must pick the same category the organizer generated, just like the
    // organizer did.
    const spectatorCategorySelect = spectatorPage.locator('select').filter({ has: spectatorPage.getByRole('option', { name: /All Divisions|Все категории/i }) });
    let spectatorRoosterOption: string | undefined;
    await expect.poll(async () => {
      const options = await spectatorCategorySelect.locator('option').allTextContents();
      spectatorRoosterOption = options.find(o => /Rooster/.test(o) && /\(\d+\/2\)/.test(o));
      return spectatorRoosterOption;
    }, { timeout: 8000 }).toBeTruthy();
    await spectatorCategorySelect.selectOption({ label: spectatorRoosterOption! });

    await expect(spectatorPage.locator('text=Spectator Visible Athlete A')).toBeVisible({ timeout: 8000 });
    await expect(spectatorPage.locator('text=Spectator Visible Athlete B')).toBeVisible({ timeout: 8000 });

    // No mutation controls: no generate-bracket button, no call-to-mat button.
    await expect(spectatorPage.getByRole('button', { name: /Build Bracket|Создать сетку/i })).toHaveCount(0);
    await expect(spectatorPage.getByRole('button', { name: /Call to Mat|Вызвать на ковер/i })).toHaveCount(0);

    // Clicking an athlete card must not open the finish-match modal.
    await spectatorPage.locator('text=Spectator Visible Athlete A').click();
    await expect(spectatorPage.getByRole('heading', { name: /Finalize Match|Завершить схватку/i })).toHaveCount(0);

    await spectatorContext.close();
  });

  test('an unknown slug shows a not-found message instead of crashing', async ({ page }) => {
    await page.goto('/?live=true&t=no-such-tournament-slug');
    await expect(page.locator('text=/not found|не найден/i')).toBeVisible({ timeout: 8000 });
  });
});
